name: publish-draft
# if there are any drafts to be posted today, publish them!

on:
  workflow_dispatch:
  schedule:
    - cron: "20 6 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Python packages
        run: |
          pip install --upgrade pip -r .github/requirements.txt

      - name: Git config
        run: |
          git config --local user.email "bot@neighborhoodscientist.org"
          git config --local user.name "yns-bot"
          git config push.default upstream
          git config push.autoSetupRemote true

      - name: Open pull request to publish any drafts due today
        id: open-pr
        run: |
          python .github/bot.py
          if [[ $(git diff --exit-code . ) ]]; then
              changes=true
              today=$(date +'%Y-%m-%d')
              branch="post/${today}"
              echo "branch=$branch" >> $GITHUB_OUTPUT
              git switch -c $branch
              git add .
              git commit -m "🤖 publish post(s) for ${today}" || echo 'nothing to commit'
              git push
              gh pr create --fill
              gh pr merge --auto --merge
          else
              changes=false
          fi
          echo "changes=$changes" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_BOT }}

      - name: Approve PR
        if: steps.open-pr.outputs.changes == 'true'
        run: |
          gh pr review $BRANCH --approve
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_KLS }}
          BRANCH: ${{ steps.open-pr.outputs.branch }}
